import './component/styledselect.html'
import './component/anchor.html'

import './component/menubar.html'
import './component/loginform.html'
import './component/yearselector.html'
import './component/map/map.html'
import './component/dyntable.html'
import './component/modal.html'
import './component/activities.html'
import './component/msgshower.html'
import './component/raw.html'
import './component/spinner.html'
import './component/spinneror.html'

import './component/perguntas/newperguntaform.html'
import './component/perguntas/perguntas.html'
import './component/comments/comments.html'
import './component/comments/comment.html'
import './component/pergcomtabs.html'

import './component/chart/charts.html'
import './component/chart/donut.html'
import './component/chart/bar.html'

import './view/pessoa-view.html'
import './view/home-view.html'
import './view/texto-view.html'
import './view/ano-view.html'
import './view/despesa-view.html'

import './app.html'
