// TODO: Remover ou otimizar load abaixo
// import 'core-js'
// import 'babel/polyfill'
// import 'es6-symbol/implement'
import 'core-js/fn/symbol'
import 'core-js/fn/array/iterator'
// import 'core-js/fn/object/assign'
// import 'core-js/fn/promise.js'
// import 'es6.array.iterator'
// import 'core-js/fn/symbol/iterator'

import 'riot'
import 'leaflet'
import 'leaflet/dist/leaflet.css'
import 'leaflet.markercluster'
import 'regeneratorRuntime'
